name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      # explicit include-based build matrix, of known valid options
      matrix:
        include:
          # 22.04 supports CUDA 11.7+
          - os:  ubuntu-latest
            cuda: "12.0"
            gcc: 11
    steps:
    - uses: actions/checkout@v4

    - name: Install CUDA
      env:
        cuda: ${{ matrix.cuda }}
      run: |
        bash ./scripts/actions/install_cuda_ubuntu.sh
      shell: bash

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: .\build\Tests\Release\Tests

