name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install CUDA
      env:
        cuda: ${{ matrix.cuda }}
      run: |
        bash ./scripts/actions/install_cuda_ubuntu.sh
      shell: bash

    - name: Configure CMake
      run: cmake -B build -S .

    - name: Build
      run: cmake --build build --config Release

    - name: Test
      run: .\build\Tests\Release\Tests

